name: test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Go ${{ matrix.go }} test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go: ["oldstable", "stable"]
        os: [macos-13, macos-14, macos-15] # https://github.com/actions/runner-images
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: |
          sw_vers
          go test -v
          go run ./cmd
